PREFIX ?= riscv64-linux-gnu-
CC := $(PREFIX)gcc
HOST := $(patsubst %-gcc,%,$(CC))
STRIP := $(PREFIX)strip
DESTDIR ?= /code/sdcard/riscv/glibc

ifneq (,$(findstring riscv64,$(PREFIX)))
    ARCH := riscv64
    CROSS_TARGET := riscv64-linux-gnu
else ifneq (,$(findstring loongarch64,$(PREFIX)))
    ARCH := loongarch64
    CROSS_TARGET := loongarch64-linux-gnu
else
    $(error "Unknown ARCH! It should be riscv64 or loongarch64")
endif

all: git busybox


git: .PHONY
	tar Jxf zlib-1.3.1.tar.xz
	tar Jxf git-2.50.1.tar.xz
ifneq (,$(findstring riscv64,$(PREFIX)))
	cd zlib-1.3.1 && CROSS_PREFIX=${CROSS_TARGET}- ./configure && make -j 16 && make DESTDIR=/usr/lib/gcc-cross/riscv64-linux-gnu/11 install
	cp /usr/lib/gcc-cross/riscv64-linux-gnu/11/usr/local/lib/libz.a /usr/lib/gcc-cross/riscv64-linux-gnu/11/
	cd git-2.50.1 && ./configure --prefix=/usr --build=${CROSS_HOST} --host=${CROSS_TARGET} --with-gitconfig=/etc/gitconfig --with-python=python3 --without-iconv                  ac_cv_fread_reads_directories=yes ac_cv_snprintf_returns_bogus=no && make -j 16 && make install
else ifneq (,$(findstring loongarch64,$(PREFIX)))
	cd zlib-1.3.1 && CROSS_PREFIX=${CROSS_TARGET}- ./configure && make -j 16 && make DESTDIR=/opt/gcc-13.2.0-loongarch64-linux-gnu/sysroot install
	cd git-2.50.1 && ./configure --prefix=/usr --build=${CROSS_HOST} --host=${CROSS_TARGET} --with-gitconfig=/etc/gitconfig --with-python=python3 --without-iconv                  ac_cv_fread_reads_directories=yes ac_cv_snprintf_returns_bogus=no && make -j 16 && make install
endif

busybox: .PHONY
	cp config/busybox-config-$(ARCH) busybox/.config
	make -C busybox CC="$(CC) -static" STRIP=$(STRIP) -j
	cp busybox/busybox $(DESTDIR)/

	
clean:
	rm -fr git-2.50.1
	rm -fr zlib-1.3.1
	make -C busybox clean
	

.PHONY: 