PREFIX ?= riscv64-linux-gnu-
CC := $(PREFIX)gcc
HOST := $(patsubst %-gcc,%,$(CC))
STRIP := $(PREFIX)strip
DESTDIR ?= /code/sdcard/riscv/glibc

ifneq (,$(findstring riscv64,$(PREFIX)))
    ARCH := riscv64
else ifneq (,$(findstring loongarch64,$(PREFIX)))
    ARCH := loongarch64
else
    $(error "Unknown ARCH! It should be riscv64 or loongarch64")
endif

all: busybox


busybox: .PHONY
	cp config/busybox-config-$(ARCH) busybox/.config
	make -C busybox CC="$(CC) -static" STRIP=$(STRIP) -j
	cp busybox/busybox $(DESTDIR)/
	
clean:
	make -C busybox clean

.PHONY: 